### ISSUE TITLE
SFML crashes when rendering a sprite

### ISSUE THREAD

**Issue by bjadamson** [jeremyletang/rust-sfml#173] opened 2017-10-11 16:31 UTC
Hi, I have put together a super minimal example that causes a segfault on my linux machine.

https://gist.github.com/bjadamson/52ed39c42acb75fe92ec594f3e46e11c

If I comment out the line:
        window.draw(&sprite);

Then the program does not crash. I have tried loading different types of sprite's, but it seems the call to draw(&sprite) crashes no matter what I do. From what I can tell.. the texture should still be alive for the duration of the program (it's created on the stack).

Any ideas?

[1]    10912 segmentation fault  cargo run

edit: I removed the user input handling code.. so in the example the code loops forever. In my code, I handle getting out of the loop... but that's not related

**Comment by crumblingstatue** [comment] 2017-10-11 20:21
Unfortunately, I can't reproduce the segfault. Valgrind _does_ complain about a conditional jump depending on an uninitialized value, but that's inside the graphics driver. This doesn't seem to be the fault of rust-sfml specifically. You could try the same code with C and CSFML perhaps.

**Comment by crumblingstatue** [comment] 2017-10-20 19:32
The following Rust, C, and C++ programs all reproduce the valgrind message I mentioned above, but I don't get a crash.

```Rust
extern crate sfml;

use sfml::window::*;
use sfml::graphics::*;

fn main() {
    let mut window = RenderWindow::new((800, 600), "test", Style::CLOSE, &Default::default());
    let texture = Texture::new(100, 100).unwrap();
    let mut sprite = Sprite::with_texture(&texture);
    window.draw(&sprite);
}   
```

```C
#include "SFML/Graphics.h"
#include "SFML/Window.h"

int main() {
    sfVideoMode mode = {800, 600, 32};
    sfContextSettings settings = {0, 0, 0, 1, 1, 0, 0};
    sfRenderWindow * window = sfRenderWindow_create(mode, "test", sfClose, &settings);
    sfTexture * texture = sfTexture_create(100, 100);
    sfSprite * sprite = sfSprite_create();
    sfSprite_setTexture(sprite, texture, 1);
    sfRenderWindow_drawSprite(window, sprite, NULL);
    return 0;
}
```

```C++
#include <SFML/Graphics.hpp>

int main() {
    sf::RenderWindow window(sf::VideoMode(800, 600), "test", sf::Style::Close);
    sf::Texture texture;
    texture.create(100, 100);
    sf::Sprite sprite(texture);
    window.draw(sprite);
}
```

**Comment by crumblingstatue** [comment] 2019-10-26 14:31
Since I can't reproduce, and there hasn't been an activity for almost 2 years, I'm closing.

**Closed by crumblingstatue** 2019-10-26 14:31 UTC
Labels: can't reproduce
