### ISSUE TITLE
Issue Running under macOS

### ISSUE THREAD

**Issue by gmisail64** [jeremyletang/rust-sfml#167] opened 2017-08-29 15:37 UTC
I have just installed the library and fixed some issues linking SFML and CSFML. When running the program, I get this error:

```
error[E0061]: this function takes 3 parameters but 2 parameters were supplied
 --> src/main.rs:7:55
  |
7 |     let mut window = RenderWindow::new(VideoMode::new(800, 600), "Hello", style::CLOSE, &Default::default());
  |                                                       ^^^^^^^^ expected 3 parameters

error: no method named `poll_event` found for type `std::option::Option<sfml::graphics::RenderWindow>` in the current scope
  --> src/main.rs:10:37
   |
10 |         while let Some(ev) = window.poll_event() {
   |                                     ^^^^^^^^^^

error: no method named `clear` found for type `std::option::Option<sfml::graphics::RenderWindow>` in the current scope
  --> src/main.rs:17:16
   |
17 |         window.clear();
   |                ^^^^^

error: no method named `display` found for type `std::option::Option<sfml::graphics::RenderWindow>` in the current scope
  --> src/main.rs:20:16
   |
20 |         window.display();
   |                ^^^^^^^

error: aborting due to 4 previous errors

error: Could not compile `retro`.
```

This is my code:

```
extern crate sfml;

use sfml::graphics::*;
use sfml::window::*;

fn main() {
    let mut window = RenderWindow::new((800, 600), "Hello", style::CLOSE, &Default::default());

    loop {
        while let Some(ev) = window.poll_event() {
            match ev {
                Event::Closed => return,
                _ => {}
            }
        }

        window.clear();
        

        window.display();
    }
}

```

I installed SFML and CSFML via brew.

Thank you

**Comment by crumblingstatue** [comment] 2017-08-29 18:46
> `let mut window = RenderWindow::new(VideoMode::new(800, 600), "Hello", style::CLOSE, &Default::default());`

VideoMode::new takes 3 arguments (width, height, bits per pixel), not 2. Interestingly, the code you posted doesn't use VideoMode::new, so it doesn't match up with the error you're getting.

As for the rest of the errors you posted, you forgot to unwrap the `Option<RenderWindow>` that you get from `RenderWindow::new`. If you don't know how to unwrap it, I suggest you learn some Rust before trying out rust-sfml.

Anyway, I'm closing this, as this is not a bug with rust-sfml.

**Closed by crumblingstatue** 2017-08-29 18:46 UTC

**Comment by gmisail64** [comment] 2017-08-29 18:51
I'm just learning Rust, thank you for pointing that out! I adapted the code from some of the examples, so there may be an issue with the examples being updated.

**Comment by crumblingstatue** [comment] 2017-08-29 18:52
> I adapted the code from some of the examples, so there may be an issue with the examples being updated.

Is it an example that belongs to the rust-sfml repository? If so, can you point me to the wrong example?

If it doesn't belong to this repository, then I can't do anything about it. I only have control over this repository.

**Comment by gmisail64** [comment] 2017-08-29 18:55
I adapted the code from the 'mouse' example in the examples folder. I removed all of the mouse related stuff to just get a window running.

**Comment by crumblingstatue** [comment] 2017-08-29 18:59
The mouse example doesn't have the errors that are in your code, so it was most likely an error on your part.

**Comment by gmisail64** [comment] 2017-08-29 19:07
I just ran the mouse example without altering any of the code. The examples don't use VideoMode nor do they unwrap the RenderWindow. I am also having issues using `&Color::BLACK`, I am getting the error: 
```
error: no associated item named `BLACK` found for type `sfml::graphics::Color` in the current scope
  --> src/main.rs:43:23
   |
43 |         window.clear(&Color::BLACK);
   |                       ^^^^^^^^^^^^
```

I haven't written any code in the library yet; I have only tried running the modified example code.

**Comment by crumblingstatue** [comment] 2017-08-29 19:30
You are looking at the examples for the `master` branch, while using the `0.12` release.

[docs.rs](https://docs.rs/crate/sfml/0.12.0/source/examples/) is probably a more beginner friendly source for examples, as it always corresponds to an actual release.

**Comment by gmisail64** [comment] 2017-08-29 19:42
Thank you so much, I totally didn't see that.
