### ISSUE TITLE
Unable to link on Windows

### ISSUE THREAD

**Issue by Flone-dnb** [jeremyletang/rust-sfml#237] opened 2021-06-06 11:24 UTC
Building on Windows with SFML 2.5.1 fails with error:

`error LNK2019: unresolved external symbol sfRenderTexture_createWithSettings referenced in function _ZN4sfml8graphics14render_texture13RenderTexture13with_settings17h6d46b3735f96e13bE`

Because I only use `audio` from SFML I've downloaded this crate locally and changed `Cargo.toml`:
`[features]
default = ["graphics", "audio"]`
to
`
[features]
default = ["audio"]
`

Now builds successfully as a temporary workaround.
All of the required `*.lib` files are indeed right where they should be.

**Comment by crumblingstatue** [comment] 2021-06-06 11:30
Duplicate of #235

**Closed by crumblingstatue** 2021-06-06 11:30 UTC
